# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-03 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_abbvr', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('company_data', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField()),
                ('stock_open', models.FloatField()),
                ('stock_close', models.FloatField()),
                ('stock_high', models.FloatField()),
                ('stock_low', models.FloatField()),
                ('stock_volume', models.BigIntegerField()),
                ('stock_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Company')),
            ],
        ),
    ]
