# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-04 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_dashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='first_company',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='first_company',
            field=models.ManyToManyField(related_name='dashboard1_requests_created', to='stock.Company'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='second_company',
            field=models.ManyToManyField(related_name='dashboard2_requests_created', to='stock.Company'),
        ),
    ]
