# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-05 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20170305_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_name', models.CharField(max_length=100)),
                ('dashboard_company_abbreviation', models.CharField(max_length=100)),
                ('dashboard_chart_type', models.CharField(max_length=100)),
                ('dashboard_chart_xaxis', models.CharField(max_length=100)),
                ('dashboard_chart_yaxis', models.CharField(max_length=100)),
                ('dashboard_chart_title', models.CharField(max_length=200)),
                ('dashboard_chart_xlabel', models.CharField(max_length=200)),
                ('dashboard_chart_ylabel', models.CharField(max_length=200)),
            ],
        ),
    ]
