# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-06 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_dashboardinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardinfo',
            name='dashboard_chart_ylabel',
        ),
        migrations.RemoveField(
            model_name='dashboardinfo',
            name='dashboard_name',
        ),
        migrations.AlterField(
            model_name='dashboardinfo',
            name='dashboard_chart_type',
            field=models.CharField(choices=[('Line', 'line'), ('Pie', 'pie'), ('Scatter', 'scatter'), ('Column', 'column')], max_length=100),
        ),
        migrations.AlterField(
            model_name='dashboardinfo',
            name='dashboard_chart_xaxis',
            field=models.CharField(choices=[('Volume', 'stock_volume'), ('Date', 'stock_date'), ('Low', 'stock_low'), ('High', 'stock_high'), ('Close', 'stock_close'), ('Open', 'stock_open')], max_length=200),
        ),
        migrations.AlterField(
            model_name='dashboardinfo',
            name='dashboard_chart_yaxis',
            field=models.CharField(max_length=500),
        ),
    ]
